"""add_release_fields

Revision ID: 40ed5c82016a
Revises: ea199c990e64
Create Date: 2026-05-24 11:44:40.400641
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40ed5c82016a'
down_revision: Union[str, None] = 'ea199c990e64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inbox_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('issue_attachments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('issue_timeline', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('issues', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('issues', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('labels', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('regression_history', 'detected_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.add_column('releases', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('releases', sa.Column('target_date', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('releases', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('releases', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('system_settings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('system_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-05-23 22:59:35.758718+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('system_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-05-23 22:59:35.758718+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('system_settings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-05-23 22:59:35.758718+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('releases', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-05-23 22:59:35.758718+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('releases', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-05-23 22:59:35.758718+00'::timestamp with time zone"),
               existing_nullable=False)
    op.drop_column('releases', 'target_date')
    op.drop_column('releases', 'description')
    op.alter_column('regression_history', 'detected_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-05-23 22:59:35.758718+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-05-23 22:59:35.758718+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('labels', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-05-23 22:59:35.758718+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('issues', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-05-23 22:59:35.758718+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('issues', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-05-23 22:59:35.758718+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('issue_timeline', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-05-23 22:59:35.758718+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('issue_attachments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-05-23 22:59:35.758718+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('inbox_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-05-23 22:59:35.758718+00'::timestamp with time zone"),
               existing_nullable=False)
    # ### end Alembic commands ###
