"""

Revision ID: 6a40d3e32678
Revises: b849450048f2
Create Date: 2026-05-23 22:22:59.418181
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a40d3e32678'
down_revision: Union[str, None] = 'b849450048f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_labels_name'), 'labels', ['name'], unique=True)
    op.alter_column('inbox_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('issue_attachments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('issue_timeline', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('issues', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('issues', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('regression_history', 'detected_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('releases', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('releases', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-05-23 22:22:52.715298+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('releases', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-05-23 22:22:52.715298+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('releases', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-05-23 22:22:52.715298+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('regression_history', 'detected_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-05-23 22:22:52.715298+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-05-23 22:22:52.715298+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('issues', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-05-23 22:22:52.715298+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('issues', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-05-23 22:22:52.715298+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('issue_timeline', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-05-23 22:22:52.715298+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('issue_attachments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-05-23 22:22:52.715298+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('inbox_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-05-23 22:22:52.715298+00'::timestamp with time zone"),
               existing_nullable=False)
    op.drop_index(op.f('ix_labels_name'), table_name='labels')
    op.drop_table('labels')
    # ### end Alembic commands ###
