"""

Revision ID: 7f60b302c290
Revises: aa11bb22cc33
Create Date: 2026-06-21 21:25:25.684678
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f60b302c290'
down_revision: Union[str, None] = 'aa11bb22cc33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('issue_attachments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('issue_cycles', 'cycle_number',
               existing_type=sa.SMALLINT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('issue_embeddings', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('issue_embeddings', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=False)
    op.alter_column('issue_embeddings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('issue_embeddings_hnsw'), table_name='issue_embeddings', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_constraint(op.f('uq_issue_embeddings_issue_group_hash'), 'issue_embeddings', type_='unique')
    op.create_unique_constraint('uq_issue_embeddings_issue_group', 'issue_embeddings', ['issue_id', 'field_group'])
    op.alter_column('issues', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('issues', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.drop_index(op.f('ix_issues_search_tsv'), table_name='issues', postgresql_using='gin')
    op.alter_column('labels', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('regression_history', 'detected_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('releases', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('releases', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    op.alter_column('telegram_integrations', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('telegram_integrations_telegram_user_id_key'), 'telegram_integrations', type_='unique')
    op.drop_constraint(op.f('telegram_integrations_user_id_key'), 'telegram_integrations', type_='unique')
    op.drop_index(op.f('ix_telegram_integrations_telegram_user_id'), table_name='telegram_integrations')
    op.create_index(op.f('ix_telegram_integrations_telegram_user_id'), 'telegram_integrations', ['telegram_user_id'], unique=True)
    op.drop_index(op.f('ix_telegram_integrations_user_id'), table_name='telegram_integrations')
    op.create_index(op.f('ix_telegram_integrations_user_id'), 'telegram_integrations', ['user_id'], unique=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='now()',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-05-26 11:09:23.342622+00'::timestamp with time zone"),
               existing_nullable=False)
    op.drop_index(op.f('ix_telegram_integrations_user_id'), table_name='telegram_integrations')
    op.create_index(op.f('ix_telegram_integrations_user_id'), 'telegram_integrations', ['user_id'], unique=False)
    op.drop_index(op.f('ix_telegram_integrations_telegram_user_id'), table_name='telegram_integrations')
    op.create_index(op.f('ix_telegram_integrations_telegram_user_id'), 'telegram_integrations', ['telegram_user_id'], unique=False)
    op.create_unique_constraint(op.f('telegram_integrations_user_id_key'), 'telegram_integrations', ['user_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('telegram_integrations_telegram_user_id_key'), 'telegram_integrations', ['telegram_user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('telegram_integrations', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('releases', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-05-26 11:09:23.342622+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('releases', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-05-26 11:09:23.342622+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('regression_history', 'detected_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-05-26 11:09:23.342622+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-05-26 11:09:23.342622+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('labels', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-05-26 11:09:23.342622+00'::timestamp with time zone"),
               existing_nullable=False)
    op.create_index(op.f('ix_issues_search_tsv'), 'issues', ['search_tsv'], unique=False, postgresql_using='gin')
    op.alter_column('issues', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-05-26 11:09:23.342622+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('issues', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-05-26 11:09:23.342622+00'::timestamp with time zone"),
               existing_nullable=False)
    op.drop_constraint('uq_issue_embeddings_issue_group', 'issue_embeddings', type_='unique')
    op.create_unique_constraint(op.f('uq_issue_embeddings_issue_group_hash'), 'issue_embeddings', ['issue_id', 'field_group', 'content_hash'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('issue_embeddings_hnsw'), 'issue_embeddings', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.alter_column('issue_embeddings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('issue_embeddings', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               existing_nullable=False)
    op.alter_column('issue_embeddings', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('issue_cycles', 'cycle_number',
               existing_type=sa.SMALLINT(),
               server_default=sa.text("'1'::smallint"),
               existing_nullable=False)
    op.alter_column('issue_attachments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-05-26 11:09:23.342622+00'::timestamp with time zone"),
               existing_nullable=False)
    # ### end Alembic commands ###
