"""duplicate hints and dismissals

Revision ID: 8ea5104b5b90
Revises: b4c5d6e7f8a9
Create Date: 2026-10-01 14:17:43.164591

Slice 14 (engine PRD Appendix A.4): stored triage hints for New bugs, and
"Not a duplicate" dismissals that outlive every recomputation (BR-S12).
Autogenerated, trimmed to the two new tables — the other detected diffs are
dev-database drift already covered by earlier revisions.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '8ea5104b5b90'
down_revision: Union[str, None] = 'b4c5d6e7f8a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('duplicate_dismissals',
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('dismissed_by_id', sa.Integer(), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['issues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dismissed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('issue_id', 'candidate_id')
    )
    op.create_table('duplicate_hints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('jev_model', sa.String(length=64), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['issues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issue_id', 'candidate_id', name='uq_duplicate_hints_pair')
    )
    op.create_index('ix_duplicate_hints_issue', 'duplicate_hints', ['issue_id'], unique=False)


def downgrade() -> None:
    op.drop_index('ix_duplicate_hints_issue', table_name='duplicate_hints')
    op.drop_table('duplicate_hints')
    op.drop_table('duplicate_dismissals')
