"""one reaction per user per comment

Revision ID: a7c4e1b93f20
Revises: 9186202809a6
Create Date: 2026-08-07

Reactions become mutually exclusive: picking a new emoji replaces the previous
one instead of stacking.  Existing rows may already violate that, so duplicates
are pruned (newest kept) before the tighter constraint goes on.

Written by hand rather than autogenerated — `alembic revision --autogenerate`
sweeps in a large amount of unrelated pre-existing drift on this schema.
"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a7c4e1b93f20'
down_revision: Union[str, None] = '9186202809a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Keep only each user's most recent reaction per comment. Ordering by
    # (created_at, id) breaks ties deterministically when timestamps collide.
    op.execute(
        """
        DELETE FROM comment_reactions a
        USING comment_reactions b
        WHERE a.timeline_id = b.timeline_id
          AND a.user_id = b.user_id
          AND (a.created_at, a.id) < (b.created_at, b.id)
        """
    )
    op.drop_constraint('uq_comment_reaction', 'comment_reactions', type_='unique')
    op.create_unique_constraint(
        'uq_comment_reaction_user', 'comment_reactions', ['timeline_id', 'user_id']
    )


def downgrade() -> None:
    # Data lost to the dedupe above cannot be restored; this only relaxes the
    # constraint so multiple emoji per user are permitted again.
    op.drop_constraint('uq_comment_reaction_user', 'comment_reactions', type_='unique')
    op.create_unique_constraint(
        'uq_comment_reaction', 'comment_reactions', ['timeline_id', 'user_id', 'emoji_key']
    )
