"""unified status model

Revision ID: b1c2d3e4f5a6
Revises: a7c4e1b93f20
Create Date: 2026-09-22

Slice 02 (docs/phase-2/02-unified-status-model.md): replaces the Phase 1
status set (new, triaged, in_progress, fixed, verified, closed, regression,
blocked) with the unified set (new, needs_info, todo, in_progress,
in_review, done, blocked, cancelled), migrates existing rows, and adds the
columns Workflow needs (cancel_reason, blocked_from_status,
review_requested_by_id, started_at, completed_at, cancelled_at). Severity
becomes nullable and drops `enhancement` (-> minor).

Written by hand rather than autogenerated, following a7c4e1b93f20's lead —
this repeats its `op.execute` data-migration style.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b1c2d3e4f5a6'
down_revision: Union[str, None] = 'a7c4e1b93f20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ── Schema ───────────────────────────────────────────────────────────────
    op.add_column('issues', sa.Column('cancel_reason', sa.String(length=32), nullable=True))
    op.add_column('issues', sa.Column('blocked_from_status', sa.String(length=32), nullable=True))
    op.add_column('issues', sa.Column('review_requested_by_id', sa.Integer(), nullable=True))
    op.add_column('issues', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('issues', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('issues', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(
        'fk_issues_review_requested_by_id_users', 'issues', 'users',
        ['review_requested_by_id'], ['id'], ondelete='SET NULL',
    )
    op.alter_column('issues', 'severity', existing_type=sa.String(length=32), nullable=True)

    # ── Data: severity ───────────────────────────────────────────────────────
    op.execute("UPDATE issues SET severity = 'minor' WHERE severity = 'enhancement'")

    # ── Data: status — simple 1:1 renames (idempotent: source values stop
    # existing once migrated, so a rerun touches zero rows) ─────────────────
    op.execute("UPDATE issues SET status = 'todo' WHERE status = 'triaged'")
    op.execute("UPDATE issues SET status = 'in_progress' WHERE status = 'regression'")

    # fixed -> in_review, review_requested_by_id = actor of the latest 'fixed' event
    op.execute("""
        UPDATE issues i
        SET status = 'in_review',
            review_requested_by_id = latest_fix.actor_id
        FROM (
            SELECT DISTINCT ON (issue_id) issue_id, actor_id
            FROM issue_timeline
            WHERE event_type = 'fixed'
            ORDER BY issue_id, created_at DESC, id DESC
        ) latest_fix
        WHERE i.id = latest_fix.issue_id AND i.status = 'fixed'
    """)
    # Any 'fixed' issue with no matching timeline event (shouldn't happen, but
    # the mapping must be total).
    op.execute("UPDATE issues SET status = 'in_review' WHERE status = 'fixed'")

    # verified -> done, completed_at = verified_at
    op.execute("UPDATE issues SET status = 'done', completed_at = verified_at WHERE status = 'verified'")

    # closed, no parent -> done, completed_at = closed_at
    op.execute("""
        UPDATE issues SET status = 'done', completed_at = closed_at
        WHERE status = 'closed' AND parent_issue_id IS NULL
    """)
    # closed, parent set (duplicate) -> cancelled
    op.execute("""
        UPDATE issues SET status = 'cancelled', cancel_reason = 'duplicate', cancelled_at = closed_at
        WHERE status = 'closed' AND parent_issue_id IS NOT NULL
    """)

    # blocked, latest status-affecting event is needs_clarification -> needs_info,
    # restoring the previous assignee from that event's meta.
    op.execute("""
        UPDATE issues i
        SET status = 'needs_info',
            assignee_id = NULLIF(latest.meta ->> 'prev_assignee_id', '')::integer
        FROM (
            SELECT DISTINCT ON (issue_id) issue_id, event_type, meta
            FROM issue_timeline
            WHERE event_type IN ('status_changed', 'needs_clarification')
            ORDER BY issue_id, created_at DESC, id DESC
        ) latest
        WHERE i.id = latest.issue_id
          AND i.status = 'blocked'
          AND latest.event_type = 'needs_clarification'
    """)
    # blocked, otherwise -> stays blocked, blocked_from_status = in_progress.
    # Guarded on blocked_from_status IS NULL so a rerun (or a future real
    # blocked row created by Workflow) is left alone.
    op.execute("""
        UPDATE issues SET blocked_from_status = 'in_progress'
        WHERE status = 'blocked' AND blocked_from_status IS NULL
    """)


def downgrade() -> None:
    # Best-effort reverse — some distinctions (verified vs. closed, the
    # needs_info reassignment, which minors were originally enhancement)
    # cannot be recovered.
    op.execute("UPDATE issues SET status = 'triaged' WHERE status = 'todo'")
    op.execute("UPDATE issues SET status = 'fixed' WHERE status = 'in_review'")
    op.execute("UPDATE issues SET status = 'verified' WHERE status = 'done'")
    op.execute("UPDATE issues SET status = 'blocked' WHERE status = 'needs_info'")
    op.execute("UPDATE issues SET status = 'closed' WHERE status = 'cancelled'")

    op.execute("UPDATE issues SET severity = 'minor' WHERE severity IS NULL")
    op.alter_column('issues', 'severity', existing_type=sa.String(length=32), nullable=False)

    op.drop_constraint('fk_issues_review_requested_by_id_users', 'issues', type_='foreignkey')
    op.drop_column('issues', 'cancelled_at')
    op.drop_column('issues', 'completed_at')
    op.drop_column('issues', 'started_at')
    op.drop_column('issues', 'review_requested_by_id')
    op.drop_column('issues', 'blocked_from_status')
    op.drop_column('issues', 'cancel_reason')
